### ISSUE TITLE
discussion: what kind of project are supposed to be in this repo

### ISSUE THREAD

**Issue by NirmalSilwal** [thetechcommunity/python#1]
Hi, seems the projects haven't been added and there has been no work being done in this community. What are the various objectives of this organization? Knowing the core goal of this community would make each of community members contribution valuable towards the open source community.

What are your thoughts on it?

Thanks

**Comment by AnkushSinghGandhi** [comment]
I apologize for the delay in replying as I had a busy schedule in the last few days. The goal of this community is to connect more and more people to open source and have their contributions respectively. 
So basically this python repository is having levels from 0 onwards. Level 0 folder is having the introduction of python followed by the open-source and level 1 is having python basic programs with comments and related assignments. I hope I explained it clearly. Feel free to ask any doubts or queries.
